version: '2.1'

services:
  parity-ropsten:
    image: parity-bin:latest
    command: '--chain ropsten --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303" --base-path /parity --rpcapi "eth,net,web3,personal,parity"'
    volumes:
      - /home/user/parity:/parity
    restart: always
    network_mode: "host"
    container_name: parity_ropsten
    healthcheck:
      test: ["CMD", "curl", "-f", "-X", "POST", "-H", "content-type:application/json",  "--data", "'{\"method\":\"eth_blockNumber\",\"params\":[],\"id\":1,\"jsonrpc\":\"2.0\"}'", "localhost:8545"]
      interval: 20s
      timeout: 10s
      retries: 12
